name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compilar:
  # criar maquina virtual para usar no pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Fazer o git clone
      uses: actions/checkout@v4
    
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo hello, world!

    - name: Run a one-line script
      run: echo Java!

    - name: Executando dois ou mais comandos
      run: |
        ls -l
        echo Fim do Processo
